"total_timesteps": 1e6
"num_envs": 16 
"num_steps": 128 
"lr": 5e-4
"anneal_lr": False
"update_epochs": 5
"num_minibatches": 2
"gamma": 0.99
"gae_lambda": 1.0
"clip_eps": 0.3
"scale_clip_eps": False
"ent_coef": 0.01
"vf_coef": 1.0
"max_grad_norm": 0.5
"activation": "tanh"
"fc_dim_size": 128
"optimizer": "adam"

env_name: "MPE_simple_tag_v3"
seed: 0
num_seeds: 5
env_kwargs: {"num_good_agents": 1, "num_adversaries": 3, "num_obs": 2}

# WandB Params
project: "mpe"
job_type: ippo_constlr
use_timestamp: True
wandb_mode: True
log_network_stats: False