_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 12
                - 45
                - 50
                - 55
            "2":
                - 12
                - 45
                - 50
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
ACTIVATION:
    value: relu
ANNEAL_LR:
    value: true
CLIP_EPS:
    value: 0.2
ENT_COEF:
    value: 0
ENTITY:
    value: ""
ENV_KWARGS:
    value:
        attack_mode: closest
        see_enemy_actions: true
        walls_cause_death: true
ENV_NAME:
    value: HeuristicEnemySMAX
FC_DIM_SIZE:
    value: 128
GAE_LAMBDA:
    value: 0.95
GAMMA:
    value: 0.99
GRU_HIDDEN_DIM:
    value: 128
LR:
    value: 0.004
MAP_NAME:
    value: 3s_vs_5z
MAX_GRAD_NORM:
    value: 0.5
NAME:
    value: ""
NUM_ENVS:
    value: 64
NUM_MINIBATCHES:
    value: 2
NUM_STEPS:
    value: 128
OBS_WITH_AGENT_ID:
    value: true
PROJECT:
    value: smax
SCALE_CLIP_EPS:
    value: false
SEED:
    value: 0
TOTAL_TIMESTEPS:
    value: 1e+07
UPDATE_EPOCHS:
    value: 2
USE_TIMESTAMP:
    value: true
VF_COEF:
    value: 0.5
WANDB_MODE:
    value: online
