"TOTAL_TIMESTEPS": 1e6
"NUM_ENVS": 16 
"NUM_STEPS": 128 
"LR": 5e-4
"ACTOR_OPTIMIZER": "adam" # adam, rmsprop
"CRITIC_OPTIMIZER": "adam" # adam, rmsprop
"ANNEAL_LR": True
"UPDATE_EPOCHS": 5
"NUM_MINIBATCHES": 2
"GAMMA": 0.99
"GAE_LAMBDA": 1.0
"CLIP_EPS": 0.3
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 1.0
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"FC_DIM_SIZE": 128
"GRU_HIDDEN_DIM": 128
"K": 2

"ENV_NAME": "MPE_simple_spread_v3"
"SEED": 0
"NUM_SEEDS": 5
"ENV_KWARGS": {}

# WandB Params
"PROJECT": "mpe"
"USE_TIMESTAMP": True
"WANDB_MODE" : "disabled" # online, disabled